### ISSUE TITLE
baseurl

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#1]
Hi @thomasjbradley I'm wondering what we will be using for the baseurl in the _config.yml file?  Right now, we are not working on a ghpages or master branch, so it isn't live.  Just going through and setting up jekyll..  But since it isn't live and the url is different than what I'm used to, I wasn't sure.

**Comment by thomasjbradley** [comment]
I’d set it to `2017` because that’s the name of the repo, like:

```yml
baseurl: "/2017"
```

That way you’ll be able to see it live at the https://algonquindesign-grads.github.io/2017 URL before we put it live.

**Comment by hellachella** [comment]
Perfect, thank you.
