### ISSUE TITLE
Page next etc

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#12]
Hi Thomas, any ideas for a fix for the page next/prev?  Right now they are not working at all :o

**Comment by thomasjbradley** [comment]
I just clone it and it works perfectly for me…
Are they just doing nothing?

**Comment by hellachella** [comment]
The urls change and are missing the /2017/ from the path when you hit next/right arrow.

Before next/right arrow
<img width="681" alt="screen shot 2017-03-09 at 7 15 34 pm" src="https://cloud.githubusercontent.com/assets/10465921/23776532/ee4efccc-04fc-11e7-997f-1804fc3d9e94.png">

After:
<img width="809" alt="screen shot 2017-03-09 at 7 15 41 pm" src="https://cloud.githubusercontent.com/assets/10465921/23776533/f3a21132-04fc-11e7-8e0f-6de30556bfa7.png">

**Comment by thomasjbradley** [comment]
`{{site.baseurl}}`?

**Comment by hellachella** [comment]
Right.  Got it.  🙃
