### ISSUE TITLE
Grad photos & performance & re-flow

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2017#16]
The grad photos are a little slow and I don't like how the whole page reflows after they load.

I’m thinking an embed container for the photo would be good to prevent the page from completely reflowing.

**Comment by robcodonnell** [comment]
By grad photos do you mean the image on the portfolio pages? Cause I have embed containers on the photos on the homepage so it should be working.

**Comment by robcodonnell** [comment]
Added embed containers to the portfolio pages.

**Comment by thomasjbradley** [comment]
I mean on the grad inside page. The photo of each person needs embed containers.

**Comment by robcodonnell** [comment]
I added them to the inside pages, should be all synced up.
