### ISSUE TITLE
site ignore

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#2]
Hey @thomasjbradley 

I'm trying to set up my .gitignore, but the interface has changed on github's app from the videos.  I've also done a search and that blew my mind. Do I just create a file called .gitignore and enter _site into it and commit that? ? I can't remember what we did?  I don't want jekyll to break.

**Comment by hellachella** [comment]
@thomasjbradley I am wondering if it's just automatic now, because I poked around and found this:

<img width="386" alt="screen shot 2017-01-25 at 8 11 36 pm" src="https://cloud.githubusercontent.com/assets/10465921/22316361/a9d4b138-e33a-11e6-93c1-89612d01b9a3.png">

<img width="736" alt="screen shot 2017-01-25 at 8 12 41 pm" src="https://cloud.githubusercontent.com/assets/10465921/22316360/a9d4196c-e33a-11e6-90e7-b5ffd82ed3c7.png">

**Comment by thomasjbradley** [comment]
Not automatic—I added that in there when I created the repository for you.

**Comment by hellachella** [comment]
Thanks!
