### ISSUE TITLE
Playing sound on video by clicking button

### ISSUE THREAD

**Issue by robcodonnell** [algonquindesign-grads/2017#22]
@thomasjbradley I'm trying to add an option to unmute the video when people click the "play sound" button with Javascript. Is there a way to toggle the "muted" property of the video by clicking the button?

**Comment by thomasjbradley** [comment]
You can target the video element and set it’s muted to `true/false`:

```js
$('video').get().muted = false;
```

**Comment by robcodonnell** [comment]
I tried writing this:
```
$('.play-sound').click(function() {
  if ($('video').get().muted = true) {
    $('video').get().muted = false;
  }
  else {
    $('video').get().muted = true;
  }
});
```
But it's not working, no errors in the console either. Am I missing something?

**Comment by thomasjbradley** [comment]
This line should have a double equals:

```js
if ($('video').get().muted == true) {
```

**Comment by robcodonnell** [comment]
I tried that, still doesn't work. Any ideas?

**Comment by thomasjbradley** [comment]
Oh, it should be `.get(0)`—put a `0` in all the `get()` methods.

**Comment by robcodonnell** [comment]
Awesome that fixed it. thanks.
