### ISSUE TITLE
prev/next.  Last grad goes to empty page. 

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#23]
@thomasjbradley 

Only happens with the arrow key. So if you hit arrow next, It doesn't go to 404 or re-loop.  Can we make that happen?  Ideally it would re-loop to the first grad.

**Comment by thomasjbradley** [comment]
I committed a change to fix it: I put if-statements around the next/prev JS & also made the grads loop around.

**Comment by hellachella** [comment]
Thanks
