### ISSUE TITLE
Page loader

### ISSUE THREAD

**Issue by robcodonnell** [algonquindesign-grads/2017#26]
Hey @thomasjbradley I'm trying to get a gif to play while the page loads, but I can't get the JS to work. I've tried this:

```
$(window).load(function() {
	$("#loader").fadeOut("slow");
});
```

**Comment by thomasjbradley** [comment]
I dunno—does `#loader` exist on the page?
That's what the error message I'm seeing I think it suggesting.

**Comment by robcodonnell** [comment]
I have it as an include, but when I include it on the homepage it stays playing at the top of the page indefinitely. Im wondering how to make it only play until everything has loaded.

**Comment by hellachella** [comment]
Thomas, would window.onload and the addClass to hide it work?

**Comment by thomasjbradley** [comment]
I dunno why, but if you change it to this, it works:

```js
$(window).on('load', function() {
  $("#loader").fadeOut("slow");
});
```

**Comment by hellachella** [comment]
It's oldskool js and I'm rusty, but like:

window.onload = loader;

var pageLoader;

function loader() {

pageLoader = document.querySelector(".loader");
  
pageLoader.className = "hidden";

}



function loadLogo

**Comment by hellachella** [comment]
Aaahhh  There we go.
