### ISSUE TITLE
Swipe left/right on mobile. 

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#28]
@thomasjbradley I'm wondering if it's possible to set the inpages so they scroll with left/right swipe?  I've never done it.

**Comment by thomasjbradley** [comment]
Yeah, I have a snippet of swiping JS code that we can implement.
Let me go digging for it…

**Comment by thomasjbradley** [comment]
Okay, I found it and put it online for you:
https://gist.github.com/thomasjbradley/c0f75648bc9282297a97d92572dcd462

You’ll need to download the `swiper.js` file—put it into your `js` folder.

Then, at the bottom of `gradlayout.html` add this code:

```html
<script src="{{site.baseurl}}/js/swiper.js"></script>
<script>
  swiper(document.body, function (e) {
    if (e.direction === 'left') {
      window.location = document.querySelector('.nxt').href;
    } else {
      window.location = document.querySelector('.prev').href;
    }
  });
</script>
```

**Comment by hellachella** [comment]
Ok, I've tried a few things.  I'm not linking it properly or something, and I'm getting this error in the console:

<img width="268" alt="screen shot 2017-03-13 at 11 49 20 am" src="https://cloud.githubusercontent.com/assets/10465921/23862371/2feb3626-07e3-11e7-8c98-6f607eae3387.png">

**Comment by thomasjbradley** [comment]
Is the `swiper.js` file in your `js` folder?

**Comment by hellachella** [comment]
<img width="208" alt="screen shot 2017-03-13 at 12 06 40 pm" src="https://cloud.githubusercontent.com/assets/10465921/23863223/8bb3d948-07e5-11e7-89e8-fb37f8e53f43.png">

**Comment by thomasjbradley** [comment]
At the top of `swiper.js` it says: `swiper.js`—delete that.

**Comment by hellachella** [comment]
Now this

<img width="253" alt="screen shot 2017-03-13 at 12 14 21 pm" src="https://cloud.githubusercontent.com/assets/10465921/23863645/a3005350-07e6-11e7-8d38-8bfff2ad38eb.png">

**Comment by thomasjbradley** [comment]
I'm going to clone and fix it—there's something missing from the `swiper.js` file.

**Comment by thomasjbradley** [comment]
Committed & synced.

**Comment by hellachella** [comment]
Thanks!

**Comment by hellachella** [comment]
{{ site.baseurl }} got me again.  lol.
