### ISSUE TITLE
CSS Branding colours.  

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#3]
Hey @robcodonnell , I stuck this into my css main as our basic branding colours.  .  

 /*Colour*/

.bg-dark-grey {
  background-color: #464646;
}

.bg-lightgrey {
  background-color: #f6f6f6
}

.bg-black {
  background-color: #000;
}

.bg-red {
  background-color: #ff6460;
}

.bg-white {
  background-color: #fff;
}

.text-grey {
  color: #464646;
}

.text-white {
  color: #fff;
}

.text-red {
  color: #ff6460;
}

.text-black {
  color: #000
}

**Comment by robcodonnell** [comment]
@hellachella Awesome! I'll add this into my css

**Comment by hellachella** [comment]
@robcodonnell I've also made the basic footer _include.  I had to use some more things from the modulifier, so you will probably have to as well to get it working on your page.  Just recopy it with everything but forms & buttons.  I used _nice lists_ which we didn't copy over before.  Here is a link:

https://modulifier.web-dev.tools/#responsive;images;list-group;embed;media-object;icons;hidden;positioning;nice-lists;accessibility;print  

I also updated the brand colours, so here is that:

 /*Colour*/

.bg-black {
  background-color: #000;
}

.bg-grey-black {
background-color: #2c2c2c;
}

.bg-ultra-dark-grey {
  background-color: #333333;
}

.bg-dark-grey {
  background-color: #464646;
}

.bg-lightgrey {
  background-color: #f6f6f6
}

.bg-red {
  background-color: #ff6460;
}

.bg-white {
  background-color: #fff;
}

.text-grey {
  color: #464646;
}

.text-white {
  color: #fff;
}

.text-red {
  color: #ff6460;
}

.text-black {
  color: #000
}
