### ISSUE TITLE
Iphone Issues

### ISSUE THREAD

**Issue by KimothyPepper** [algonquindesign-grads/2017#30]
So the only thing I could find on iphone was that on landscape view the GR of GRAD gets cut off by the nav in all browsers (but its only minor?) ALSO on mobile there is a play button for the video which doesn't work in any of the browsers..The sound on/off buttons plays the video

![chrome](https://cloud.githubusercontent.com/assets/10464620/23904141/33d6eb62-089d-11e7-9c3d-146471349981.jpg)
![opera](https://cloud.githubusercontent.com/assets/10464620/23904142/33e73558-089d-11e7-9128-06b0b2e47d6e.jpg)

**Comment by hellachella** [comment]
@robcodonnell
