### ISSUE TITLE
Browser: Firefox 48.0.2

### ISSUE THREAD

**Issue by jenniferyaya** [algonquindesign-grads/2017#31]
Three column-grid disappears:

<img width="1680" alt="screen shot 2017-03-14 at 12 56 01" src="https://cloud.githubusercontent.com/assets/10467649/23912341/b705df1c-08b5-11e7-983e-531cd90f42b2.png">

**Comment by hellachella** [comment]
@robcodonnell 3 column still disappearing in Firefox.

**Comment by hellachella** [comment]
Fixed
