### ISSUE TITLE
Nav- linking to next and previous

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#5]
Hi @thomasjbradley 
I wish I'd have thought to ask this on Friday,

I'm wondering about how I link the pages to each other in the navigation.  Should I wait for this step or is it straight forward enough?

C

**Comment by thomasjbradley** [comment]
Try this:

```html
{% capture the_collection %}{{page.collection}}{% endcapture %}

{% if page.collection %}
  {% assign  document = site[the_collection]  %}
{% endif %}

{% for links in document  %}
  {% if links.title == page.title %}
    {% unless forloop.first %}
      {% assign prevurl = prev.url %}
    {% endunless %}
    {% unless forloop.last %}
      {% assign next = document[forloop.index] %}
      {% assign nexturl = next.url %}
    {% endunless %}
  {% endif %}
  {% assign prev = links %}
{% endfor %}

{% if prevurl %}<a href="{{prevurl}}" class="prev">Prev {{prevurl}}</a>{% endif %}
{% if nexturl %}<a href="{{nexturl}}" class="nxt">Next {{nexturl}}</a>{% endif %}
```

The actual links, that you'll want to style, are the very last two lines.

**Comment by hellachella** [comment]
That worked, but with one glitch..  It is including the url path in the string displayed in the browser..


<img width="606" alt="screen shot 2017-02-20 at 1 36 42 am" src="https://cloud.githubusercontent.com/assets/10465921/23114457/372ef56c-f70d-11e6-8ebc-44c4efb506f2.png">

**Comment by hellachella** [comment]
@thomasjbradley 

I fixed it by adding a span with a hidden class around the {{prevurl}}.. is that the best way to do it?

**Comment by thomasjbradley** [comment]
You could also remove the second `{{prevurl}}` from inside the `<a>` tag itself—just leaving the one in the `href=""`.
