### ISSUE TITLE
Grad photos - looping through pages

### ISSUE THREAD

**Issue by robcodonnell** [algonquindesign-grads/2017#6]
Hey @thomasjbradley, I'm trying to loop through the grads' md files to output the photo, name and url for the grad photos section on the homepage. The code I have is:

```
<ul class="gp-designer filter-items">
    {% for designer in site.designers %}
    <li class="gp-photo" data-category="{{designer.specialization[0]}} {{designer.specialization[1]}} {{designer.specialization[2]}}">
      <a href="{{site.baseurl}}/{{designer.slug}}">
        <img class="" src="https://grads.images.algonquindesign.ca/2017/portraits-square/{{designer.slug}}.jpg" alt="Portrait of {{designer.longname-oneline}}">
        <p class="gp-shortname">{{designer.shortname}}</p>
      </a>
    </li>
    {% endfor %}
  </ul>
```

Nothing inside the ul is being output so there must be something wrong with the syntax of my for loop, I'm hoping you could help me out.

Thanks

**Comment by robcodonnell** [comment]
`  <ul class="ph-student filter-items ph-padding">
    {% for student in site.grads %}
    <li class="ph-image" data-category="{{student.specialization[0]}} {{student.specialization[1]}} {{student.specialization[2]}}">
      <a href="{{site.baseurl}}{{student.url}}">
        <img class="img-flex ph-gradphoto-top" src="{{site.cdn}}portraits-thumb/{{student.url | replace: 'grads/', '/' | remove:'/'}}.jpg" alt="{{student.full_name}}">
        <p class="ph-fullname">{{student.full_name}}</p>
        <p aria-hidden="true" class="ph-partialname">{{student.short_name}}</p>
      </a>
    </li>
    {% endfor %}
  </ul>`

* actual code

**Comment by robcodonnell** [comment]
` 
<ul class="ph-student filter-items ph-padding">
    {% for student in site.grads %}
    <li class="ph-image" data-category="{{student.specialization[0]}} {{student.specialization[1]}} {{student.specialization[2]}}">
      <a href="{{site.baseurl}}{{student.url}}">
        <img class="img-flex ph-gradphoto-top" src="{{site.cdn}}portraits-thumb/{{student.url | replace: 'grads/', '/' | remove:'/'}}.jpg" alt="{{student.full_name}}">
        <p class="ph-fullname">{{student.full_name}}</p>
        <p aria-hidden="true" class="ph-partialname">{{student.short_name}}</p>
      </a>
    </li>
    {% endfor %}
  </ul>
`

**Comment by robcodonnell** [comment]
```<ul class="gp-designer filter-items">
    {% for page in site.pages %}
    <li class="gp-photo" data-category="{{page.specialty-1}} {{page.specialty-2}} {{page.specialty-3}}">
      <a href="{{site.baseurl}}/{{page.slug}}">
        <img class="" src="https://grads.images.algonquindesign.ca/2017/portraits-rectangle/{{page.slug}}.jpg" alt="Portrait of {{page.longname-oneline}}">
        <p class="gp-shortname">{{page.shortname}}</p>
      </a>
    </li>
    {% endfor %}
  </ul>
```

*actual code

**Comment by thomasjbradley** [comment]
Are you getting the errors about the `grad` layout not existing?
I think that could be causing it. When I added an empty `grads.html` layout into the `_layouts` folder the people show up on the homepage.

**Comment by robcodonnell** [comment]
Ok that worked! I totally didn't notice there was no grad layout, thanks a bunch!
