### ISSUE TITLE
Filter by specialization

### ISSUE THREAD

**Issue by robcodonnell** [algonquindesign-grads/2017#7]
Hey @thomasjbradley I'm having trouble figuring out how to filter grads by their specialization on the homepage. I've taken the code from last years site as I want to have something similar, but I can't figure out how to work the css. 

I plan on using the dropdown menu for all screen sizes, and when a specialization is selected all the grads that don't match that specialization will go to a .5 opacity. What I can't figure out is how to change the css of the photos once an option is selected from the dropdown menu. Would you mind taking a look?

Thanks.

**Comment by thomasjbradley** [comment]
I’m not sure we can do it exclusively with CSS if we’re using the `<select>` box. Mainly because we can’t use the sibling selector `~` because the `<option>` tags can’t be beside any other elements.

If you want to use `<select>` we’ll have to use Javascript.

**Comment by robcodonnell** [comment]
@thomasjbradley Ok so I'm trying to figure out the Javascript for using the select box, and it seems to me like I should use the addClass function to add a class to the corresponding data-category once an option is selected from the select box. The thing I can't figure out is how to create a variable for the data-categories so that I can add a class to them once an option is selected. Am I going about this the right way? If so do you know how to target the data-categories in JS?

**Comment by robcodonnell** [comment]
I've almost got it I think. I'm trying to make everything except branding get a .4 opacity when the branding option is selected, but it's not working yet. Am I missing something? 

Here's what my JS looks like currently
<img width="696" alt="screen shot 2017-03-05 at 2 08 46 pm" src="https://cloud.githubusercontent.com/assets/10464622/23590408/618fe8f2-01ad-11e7-9b28-5cd442b1d6ba.png">

**Comment by thomasjbradley** [comment]
You’re close—you have most of the right bits. We just need to move things around a little.
All the variables at the top are perfect, keep those. We’re going to change the function a little bit.

Delete this line, though we’re going to use a variation in a minute:
https://github.com/algonquindesign-grads/2017/blob/index/js/main.js#L10

Then add this after the variables, replacing the `function` you have there:

```js
var $all = $('.gp-photo');

$('#filter-select').on('change', function () {
  $all.css('opacity', 1);
  
  switch ($(this).val()) {
    case 'filter-branding':
      $dataBranding.css('opacity', .4);
    // Add all the remaining `case` statements in here
  }
});
```

**Comment by robcodonnell** [comment]
Awesome thank you so much. I've input this code but I'm still not seeing any change to opacity once an option is selected, have I written this correctly?

```
var $dataBranding = $('[data-category*=branding]');
var $dataWeb = $('[data-category*=web]');
var $dataPrint = $('[data-category*=print]');
var $dataType = $('[data-category*=type]');
var $dataUx = $('[data-category*=ux-ui]');
var $dataExp = $('[data-category*=experience]');
var $dataPhoto = $('[data-category*=photo]');
var $dataIll = $('[data-category*=illustration]');
var $dataMotion = $('[data-category*=motion]');

var $all = $('.gp-photo');

$('#filter-select').on('change', function () {
  $all.css('opacity', 1);

  switch ($(this).val()) {
    case 'filter-branding':
      $dataBranding.css('opacity', .4);
    case 'filter-web':
      $dataWeb.css('opacity', .4);
    case 'filter-print':
      $dataPrint.css('opacity', .4);
    case 'filter-type':
      $dataType.css('opacity', .4);
    case 'filter-ux':
      $dataUx.css('opacity', .4);
    case 'filter-experience':
      $dataExp.css('opacity', .4);
    case 'filter-photo':
      $dataPhoto.css('opacity', .4);
    case 'filter-illustration':
      $dataIll.css('opacity', .4);
    case 'filter-motion':
      $dataMotion.css('opacity', .4);
  }
});

```

**Comment by thomasjbradley** [comment]
Oh! I forgot the `break` command. Each `case` needs to end with `break;` like this:

```js
case 'filter-branding':
  $dataBranding.css('opacity', .4);
  break;
```

**Comment by robcodonnell** [comment]
Still not seeing any results! Any idea what could be going wrong?

**Comment by thomasjbradley** [comment]
Any error messages in console?

**Comment by robcodonnell** [comment]
Yep its saying $ isn't defined which means the jquery script isn't linked right? I have this in my layout but it still isn't working.

``` 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
```

**Comment by robcodonnell** [comment]
Fixed it. Just needed to put the script in the index file instead of the home.html layout. Thanks for all your help!

**Comment by thomasjbradley** [comment]
Glad you got it working!

**Comment by hellachella** [comment]
I've been following this (I get emails) and I'm pretty excited.  Thanks for your hard work Rob, and thanks @thomasjbradley.
