### ISSUE TITLE
Images from CDN not showing up

### ISSUE THREAD

**Issue by robcodonnell** [algonquindesign-grads/2017#8]
@thomasjbradley I'm having an issue with 4 of the grad photos not showing up on the homepage, even though they're in the CDN folder. Which is weird because I saw them showing up a few days ago. It's just Sage Mosurinjohn, Ashley Murray, me and Stephanie paiement. Do you know what could be causing this?

**Comment by thomasjbradley** [comment]
They seem to work for me:

![screen shot 2017-03-06 at 3 40 35 pm](https://cloud.githubusercontent.com/assets/105192/23628740/4cba5666-0283-11e7-8079-2411628e0927.png)

Caching on your computer maybe..?

**Comment by robcodonnell** [comment]
We replaced them in the CDN so they're all good now.
